/**
 * 统一错误码定义
 *
 * 命名规则：{模块}_{错误类型}
 * 所有 API 错误响应必须携带对应的错误码
 */
export const ErrorCode = {
  // ─── 通用 ───────────────────────────────
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',

  // ─── 认证 (AUTH) ─────────────────────────
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_PHONE_ALREADY_EXISTS: 'AUTH_PHONE_ALREADY_EXISTS',

  // ─── 客户 (CUSTOMER) ─────────────────────
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_PHONE_DUPLICATE: 'CUSTOMER_PHONE_DUPLICATE',

  // ─── 宠物 (PET) ─────────────────────────
  PET_NOT_FOUND: 'PET_NOT_FOUND',
  PET_NOT_BELONG_TO_CUSTOMER: 'PET_NOT_BELONG_TO_CUSTOMER',

  // ─── 服务 (SERVICE) ─────────────────────
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
  SERVICE_IN_USE: 'SERVICE_IN_USE',

  // ─── 预约 (APPOINTMENT) ────────────────
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_STATUS_INVALID: 'APPOINTMENT_STATUS_INVALID',
  APPOINTMENT_TIME_CONFLICT: 'APPOINTMENT_TIME_CONFLICT',

  // ─── 支付 (PAYMENT) ────────────────────
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',

  // ─── 寄养 (BOARDING) ───────────────────
  BOARDING_NOT_FOUND: 'BOARDING_NOT_FOUND',
  BOARDING_CAGE_OCCUPIED: 'BOARDING_CAGE_OCCUPIED',

  // ─── 会员卡 (CARD) ─────────────────────
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_BALANCE_INSUFFICIENT: 'CARD_BALANCE_INSUFFICIENT',
  CARD_TIMES_INSUFFICIENT: 'CARD_TIMES_INSUFFICIENT',
  CARD_EXPIRED: 'CARD_EXPIRED',

  // ─── 库存 (INVENTORY) ──────────────────
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  STOCK_INSUFFICIENT: 'STOCK_INSUFFICIENT',

  // ─── 文件上传 (UPLOAD) ─────────────────
  UPLOAD_FILE_TOO_LARGE: 'UPLOAD_FILE_TOO_LARGE',
  UPLOAD_FILE_TYPE_INVALID: 'UPLOAD_FILE_TYPE_INVALID',
} as const

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode]
